version: '3'


services:

  back_end:
    container_name: server
    build:
      context: .
      dockerfile: Back/dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3010:3010

  client:
    container_name: client
    build:
      context: .
      dockerfile: Front/dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000