FROM node:13.12.0-alpine

WORKDIR /Front

ENV PATH /app/node_modules/.bin:$PATH

COPY Front/package.json ./

COPY Front/package-lock.json ./

RUN npm i

COPY Front/. .

EXPOSE 3000

CMD [ "npm", "start" ]

